name: Deploy Cloud Function

on:
  push:
    branches:
      - meal_recommendation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          pip install -r meal_recommendation/requirements.txt

      - name: Copy function code
        run: |
          cp -r meal_recommendation/* $GITHUB_WORKSPACE/

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        run: gcloud auth login

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy MEAL_RECOMMENDATION \
            --runtime python38 \
            --trigger-http \
            --region us-central1
