name: Angular GitHub CI/CD

on:
  push:
    branches:
      - main
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: Frontend/FrontendMYREST # Cambia al directorio donde se encuentra package.json

      - name: Build
        run: npm run build --configuration=production
        working-directory: Frontend/FrontendMYREST # Cambia al directorio donde se encuentra package.json

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS }}
          publish_dir: Frontend/FrontendMYREST/dist/frontend-myrest # Cambia la ruta del directorio de publicación
          enable_jekyll: true